"""Generate the archetype tagging workbook.

    python3 scripts/make-tag-sheet.py [output.xlsx]

Produces a three-sheet workbook:

  Instructions  how to fill it in
  Tags          the tag vocabulary, defined by hand
  Archetypes    one row per archetype, tags chosen from that vocabulary

The tag columns are dropdowns bound to the Tags sheet, so a tag can only be
applied after it has been defined and typos cannot silently create new tags.
Re-running the script rebuilds the workbook from scratch — it does not merge
into an existing one.
"""

import json
import sys
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

ROOT = Path(__file__).resolve().parent.parent
NAMES_FILE = ROOT / "src/data/archetype-names.json"
SETCODES_FILE = ROOT / "src/data/archetype-setcodes.json"
AGES_FILE = ROOT / "src/data/archetype-ages.json"

TAG_COLUMNS = 8
TAG_VOCAB_ROWS = 120

# Archetypes sheet layout. The Tags sheet counts usage across the tag columns,
# so both sheets have to agree on where they are — derive, never hardcode.
KEEP_COL = 8
FIRST_TAG_COL = 9
LAST_TAG_COL = FIRST_TAG_COL + TAG_COLUMNS - 1

FONT = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="111B31")
FILL_ME_FILL = PatternFill("solid", fgColor="FFF9DB")
EXAMPLE_FILL = PatternFill("solid", fgColor="EEEEEE")
THIN = Side(style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)


def style_header(sheet, row: int, last_column: int) -> None:
    for column in range(1, last_column + 1):
        cell = sheet.cell(row=row, column=column)
        cell.font = Font(name=FONT, bold=True, color="FFFFFF")
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(vertical="center")
        cell.border = BORDER
    sheet.row_dimensions[row].height = 22


def build_instructions(sheet) -> None:
    sheet.sheet_view.showGridLines = False
    lines = [
        ("Archetype tagging", True, 14),
        ("", False, 11),
        ("Fill in two sheets, in this order.", False, 11),
        ("", False, 11),
        ("1. Tags — define the vocabulary", True, 12),
        ("Every tag you intend to use, one per row. Category is yours to define; it only", False, 11),
        ("groups tags in this sheet and does not reach the app. Delete the EXAMPLE row.", False, 11),
        ("", False, 11),
        ("2. Archetypes — mark what is real, then tag it", True, 12),
        ("One row per setcode in EDOPro's table. Two jobs per row:", False, 11),
        ("  keep     yes if someone actually builds this; no if it is a card-text marker", False, 11),
        ("           (Abyss Script, of-the-forest, Armored Xyz) rather than a deck.", False, 11),
        ("  tag1-8   dropdowns listing whatever you defined on the Tags sheet.", False, 11),
        ("Leave unused tag columns blank; order within a row does not matter.", False, 11),
        ("", False, 11),
        ("Generated columns are there to help you judge:", False, 11),
        ("  cards     how many distinct cards carry this setcode", False, 11),
        ("  part_of   the parent archetype, when this is a branch of one", False, 11),
        ("  debut     month the first card appeared; pre-2019 means older than", False, 11),
        ("            the card database's own history goes", False, 11),
        ("  last_new  month the most recent card appeared — the best signal for", False, 11),
        ("            whether the archetype is still being supported", False, 11),
        ("  new_12m   cards added in the last twelve months", False, 11),
        ("Card count is a hint, not an answer: Eldlich shows 2 because its spells and", False, 11),
        ("traps sit under Golden Land, and of-the-forest shows 8 while being no deck at", False, 11),
        ("all. Sort by it to move fast, but the call is yours.", False, 11),
        ("", False, 11),
        ("Format", True, 12),
        ("A tag is a short lowercase slug. In code it becomes a plain string, so keep it", False, 11),
        ("stable once used: renaming means re-tagging every archetype that carries it.", False, 11),
        ("", False, 11),
        ("Worked example of a filled row (this is format only, not a suggested taxonomy):", False, 11),
        ("    id = blue-eyes    name = Blue-Eyes    tag1 = <your tag>    tag2 = <your tag>", False, 10),
        ("", False, 11),
        ("Yellow cells are the ones to edit. Everything else is generated.", False, 11),
        ("", False, 11),
        ("Do not edit", True, 12),
        ("id, name, cards and part_of. They are regenerated by npm run sync:archetypes,", False, 11),
        ("and id keys the import back into code — editing it orphans the row.", False, 11),
        ("", False, 11),
        ("Where this list comes from", True, 12),
        ("Project Ignis' own data, pulled fresh by npm run sync:archetypes:", False, 11),
        ("  names and setcodes   ProjectIgnis/Distribution, config/strings.conf", False, 11),
        ("  card counts          ProjectIgnis/BabelCDB, cards.cdb (official only)", False, 11),
        ("Every setcode with at least one card is listed, so nothing is prejudged. The", False, 11),
        ("149 setcodes with no cards behind them are already left out.", False, 11),
    ]
    for index, (text, bold, size) in enumerate(lines, start=1):
        cell = sheet.cell(row=index, column=1, value=text)
        cell.font = Font(name=FONT, bold=bold, size=size)
    sheet.column_dimensions["A"].width = 95


def build_tags(sheet) -> None:
    headers = ["tag", "category", "description", "used_by"]
    for column, header in enumerate(headers, start=1):
        sheet.cell(row=1, column=column, value=header)
    style_header(sheet, 1, len(headers))

    # One example row showing the expected shape. Deliberately generic — the
    # vocabulary itself is the user's to decide.
    example = ["example-tag", "example-category", "Delete this row once you start."]
    for column, value in enumerate(example, start=1):
        cell = sheet.cell(row=2, column=column, value=value)
        cell.font = Font(name=FONT, italic=True, color="808080")
        cell.fill = EXAMPLE_FILL
        cell.border = BORDER

    last_archetype_row = 1 + len(load_entries())
    tag_first = get_column_letter(FIRST_TAG_COL)
    tag_last = get_column_letter(LAST_TAG_COL)
    for row in range(2, TAG_VOCAB_ROWS + 2):
        for column in range(1, 4):
            cell = sheet.cell(row=row, column=column)
            cell.font = Font(name=FONT)
            cell.border = BORDER
            if row > 2:
                cell.fill = FILL_ME_FILL
        # Blank out the count on empty rows so an empty criteria does not
        # count every empty cell in the range.
        count = sheet.cell(
            row=row,
            column=4,
            value=(
                f'=IF(A{row}="","",'
                f"COUNTIF(Archetypes!${tag_first}$2:${tag_last}${last_archetype_row},A{row}))"
            ),
        )
        count.font = Font(name=FONT)
        count.border = BORDER
        count.alignment = Alignment(horizontal="center")

    for column, width in zip("ABCD", (26, 20, 52, 10)):
        sheet.column_dimensions[column].width = width
    sheet.freeze_panes = "A2"


def build_archetypes(sheet, entries: list[dict], meta: dict, ages: dict) -> None:
    headers = (
        ["id", "name", "cards", "part_of", "debut", "last_new", "new_12m", "keep"]
        + [f"tag{i}" for i in range(1, TAG_COLUMNS + 1)]
        + ["tag_count", "notes"]
    )
    for column, header in enumerate(headers, start=1):
        sheet.cell(row=1, column=column, value=header)
    style_header(sheet, 1, len(headers))

    keep_col = KEEP_COL
    first_tag_col = FIRST_TAG_COL
    last_tag_col = LAST_TAG_COL
    count_col = last_tag_col + 1
    notes_col = count_col + 1

    for offset, archetype in enumerate(entries):
        row = offset + 2
        info = meta.get(archetype["id"], {})

        age = ages.get(archetype["id"], {})
        # Generated columns: read-only context for the judgement call.
        for column, value in (
            (1, archetype["id"]),
            (2, archetype["name"]),
            (3, info.get("cards")),
            (4, info.get("parent", "")),
            (5, "pre-2019" if age.get("legacy") else age.get("firstSeen", "")),
            (6, age.get("lastNewCard", "")),
            (7, age.get("newCards12m")),
        ):
            cell = sheet.cell(row=row, column=column, value=value)
            cell.font = Font(name=FONT, color="595959")
            cell.border = BORDER
            if column in (3, 5, 6, 7):
                cell.alignment = Alignment(horizontal="center")

        for column in (keep_col, *range(first_tag_col, last_tag_col + 1), notes_col):
            cell = sheet.cell(row=row, column=column)
            cell.font = Font(name=FONT)
            cell.fill = FILL_ME_FILL
            cell.border = BORDER
            if column == keep_col:
                cell.alignment = Alignment(horizontal="center")

        first = get_column_letter(first_tag_col)
        last = get_column_letter(last_tag_col)
        count = sheet.cell(row=row, column=count_col, value=f"=COUNTA({first}{row}:{last}{row})")
        count.font = Font(name=FONT)
        count.border = BORDER
        count.alignment = Alignment(horizontal="center")

    # Dropdowns bound to the Tags sheet, so only defined tags can be applied.
    tag_validation = DataValidation(
        type="list",
        formula1=f"=Tags!$A$2:$A${TAG_VOCAB_ROWS + 1}",
        allow_blank=True,
        showDropDown=False,
    )
    tag_validation.error = "Define the tag on the Tags sheet first."
    tag_validation.errorTitle = "Unknown tag"
    tag_validation.prompt = "Pick a tag defined on the Tags sheet."
    sheet.add_data_validation(tag_validation)
    tag_validation.add(
        f"{get_column_letter(first_tag_col)}2:"
        f"{get_column_letter(last_tag_col)}{len(entries) + 1}"
    )

    keep_validation = DataValidation(
        type="list", formula1='"yes,no"', allow_blank=True, showDropDown=False
    )
    keep_validation.prompt = "Is this a deck someone actually builds?"
    sheet.add_data_validation(keep_validation)
    keep_validation.add(
        f"{get_column_letter(keep_col)}2:{get_column_letter(keep_col)}{len(entries) + 1}"
    )

    for column, width in (
        ("A", 24), ("B", 28), ("C", 8), ("D", 18),
        ("E", 10), ("F", 10), ("G", 9), ("H", 8),
    ):
        sheet.column_dimensions[column].width = width
    for column in range(first_tag_col, last_tag_col + 1):
        sheet.column_dimensions[get_column_letter(column)].width = 16
    sheet.column_dimensions[get_column_letter(count_col)].width = 11
    sheet.column_dimensions[get_column_letter(notes_col)].width = 36
    sheet.freeze_panes = "F2"
    sheet.auto_filter.ref = f"A1:{get_column_letter(notes_col)}{len(entries) + 1}"


def load_entries() -> list[dict]:
    """Archetypes ordered by card count, biggest first.

    The sheet is worked top-down — the largest setcodes are unambiguously real
    decks and the tail is where the card-text markers live — so sorting by size
    puts the judgement calls together instead of scattering them alphabetically.
    Excel's filter row can restore A-Z whenever that is more useful.
    """
    entries = json.loads(NAMES_FILE.read_text())
    meta = load_meta()
    entries.sort(key=lambda e: (-meta.get(e["id"], {}).get("cards", 0), e["name"].lower()))
    return entries


def load_ages() -> dict:
    try:
        return json.loads(AGES_FILE.read_text())
    except FileNotFoundError:
        return {}


def load_meta() -> dict:
    try:
        return json.loads(SETCODES_FILE.read_text())
    except FileNotFoundError:
        return {}


def main() -> None:
    entries = load_entries()
    meta = load_meta()
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "archetype-tags.xlsx"

    workbook = Workbook()
    build_instructions(workbook.active)
    workbook.active.title = "Instructions"
    build_tags(workbook.create_sheet("Tags"))
    build_archetypes(workbook.create_sheet("Archetypes"), entries, meta, load_ages())

    workbook.save(out)
    print(f"Wrote {out} — {len(entries)} archetypes, {TAG_COLUMNS} tag columns")


if __name__ == "__main__":
    main()
