import type { Archetype } from '../engine/types';
import names from './archetype-names.json';
import setcodes from './archetype-setcodes.json';
import tags from './archetype-tags.json';

/**
 * Archetype registry — the card families decks are built from.
 *
 * Everything here is generated by `npm run sync:archetypes` and
 * `npm run sync:facts` from Project Ignis' strings.conf and cards.cdb. Do not
 * hand-edit: ids are stored rather than derived because slugs collide
 * ("Abyss" and "Abyss-" are separate setcodes).
 */
type SetcodeEntry = { setcodes: number[]; cards: number; parent?: string };

const META = setcodes as Record<string, SetcodeEntry>;
const TAGS = tags as Record<string, string[]>;

/**
 * Walk parent links to the root of a setcode family.
 *
 * A player names one member and answers about another — the Rainbow Dragon
 * Fusions belong to Ultimate Crystal, not Crystal Beast, though both sit under
 * Crystal — so the family is what a guess is really aiming at.
 */
function rootOf(id: string): string {
  const seen = new Set<string>();
  let current = id;
  for (;;) {
    const parent = META[current]?.parent;
    // Guard against a cycle in generated data rather than hanging on it.
    if (!parent || seen.has(parent)) return current;
    seen.add(parent);
    current = parent;
  }
}

export const ARCHETYPES: Archetype[] = names.map(({ id, name }) => {
  const meta = META[id];
  const parent = meta?.parent;
  return {
    id,
    name,
    family: rootOf(id),
    cards: meta?.cards ?? 0,
    tags: TAGS[id] ?? [],
    ...(parent ? { parent } : {}),
  };
});

export const ARCHETYPES_BY_ID: ReadonlyMap<string, Archetype> = new Map(
  ARCHETYPES.map((a) => [a.id, a]),
);

/** Every archetype sharing a family root, largest first. */
export function familyOf(id: string): Archetype[] {
  const root = ARCHETYPES_BY_ID.get(id)?.family;
  if (!root) return [];
  return ARCHETYPES.filter((a) => a.family === root).sort((a, b) => b.cards - a.cards);
}
