import type { Archetype } from '../engine/types';
import names from './archetype-names.json';

/**
 * Archetype registry — the card families, not the decks.
 *
 * Reference data: an archetype is a building block a deck is made from, so
 * nothing here is tagged, rated or recommended. Playable decks live in
 * `decks.ts` and point back at these ids.
 *
 * Generated by `npm run sync:archetypes` from Project Ignis' strings.conf and
 * cards.cdb — do not hand-edit. Ids are stored rather than derived from the
 * name, because slugs collide: EDOPro has both "Abyss" and "Abyss-".
 */
export const ARCHETYPES: Archetype[] = names;

export const ARCHETYPES_BY_ID: ReadonlyMap<string, Archetype> = new Map(
  ARCHETYPES.map((a) => [a.id, a]),
);
