import type { Card } from '../engine/types';
import cards from './cards.json';

/**
 * Card info fetched from YGOPRODeck, keyed by exact card name.
 *
 * Generated by `npm run sync:cards` — do not hand-edit. Images live in
 * `public/cards/` rather than being hotlinked, which is what YGOPRODeck asks
 * of API consumers.
 */
export const CARDS: Record<string, Card> = cards as Record<string, Card>;

export function cardByName(name: string): Card | null {
  return CARDS[name] ?? null;
}

/** Local path to a card's art, or null when it has not been synced. */
export function cardImage(card: Card): string | null {
  return card.imageId ? `${import.meta.env.BASE_URL}cards/${card.imageId}.jpg` : null;
}
